### ISSUE TITLE
patch_vid not working

### ISSUE THREAD

**Issue by jpph** [polhenarejos/pico-openpgp#1]
Hello,
The script patch_vid seems not working (the regex is wrong). File is not modified. I had to use a hexeditor and modify the file by hand.
Regards,

**Comment by polhenarejos** [comment]
Solved in 418fa9c14380067cff673cfb7000d7838956c038

**Comment by petergeher** [comment]
It doesn't work on 1.10.
At 1.8 already.

Any ideas?

./patch_vidpid.sh 1050:0406 pico_openpgp_waveshare_rp2040_zero-1.10.uf2 yub_openpgp.uf2
[…]
Patching pico_openpgp_waveshare_rp2040_zero-1.10.uf2... Patched file was saved in yub_openpgp.uf2

sudo picotool load -v -x yub_openpgp.uf2 -t uf2

lsusb|grep Pico
Bus 001 Device 055: ID feff:fcfd Pol Henarejos Pico Key
