### ISSUE TITLE
gpg --card-edit -> admin -> factory-reset blocks CHV1, CHV2, CHV3 PIN retry counter

### ISSUE THREAD

**Issue by rrottmann** [polhenarejos/pico-openpgp#4]
When doing a factory-reset using gpg --card-edit -> admin -> factory-reset all PIN counters get blocked. They were 3 3 3 before.
Is there an APDU custom-command needed to reset the variables?

Reset of course works with pico_nuke_waveshare_rp2040_zero-1.0.uf2 but this requires somewhat "knowledge" about flashing the pico and the need to nuke the flash.

The gpg factory-reset uses upstream documented process of the OpenPGP Card specification and would be doable by a less experienced/regular user.

**Comment by polhenarejos** [comment]
Cannot reproduce. Did you get an error when did factory-reset command?

To reset the PIN it can be done with `gpg --edit-card > unblock` command using the RC code (`12345678` default)

**Comment by polhenarejos** [comment]
In step `10` I get 3 3 3. 
In step `14` PIN retries are 2 3 3.

Are you using the latest firmware?

**Comment by rrottmann** [comment]
Yes, the firmware is latest. Could it be related to using Waveshare RP2040 Zero?

**Comment by polhenarejos** [comment]
Really strange. I tried hundreds of combinations and I cannot reproduce it. I'll finish the tests and see if they pass on waveshare.

**Comment by polhenarejos** [comment]
Can you try with the latest commit? I pushed lots of fixes.
I also pushed a battery set from gnuk. Give it a try to see if some test fails.

**Comment by polhenarejos** [comment]
Lots of bugfixes since then.

Please reopen if still happens with latest version.
